BEGIN TRANSACTION;

  -- CABLE
  UPDATE ra_asn SET asn_access_type = 'CABLE' where asn = 7922;
  UPDATE ra_asn SET asn_access_type = 'CABLE' where asn = 6830;
  UPDATE ra_asn SET asn_access_type = 'CABLE' where asn = 9143;
  UPDATE ra_asn SET asn_access_type = 'CABLE' where asn = 5089;
  UPDATE ra_asn SET asn_access_type = 'CABLE' where asn = 31334;
  UPDATE ra_asn SET asn_access_type = 'CABLE' where asn = 20825;
  UPDATE ra_asn SET asn_access_type = 'CABLE' where asn = 6848;
  UPDATE ra_asn SET asn_access_type = 'CABLE' where asn = 21502;
  UPDATE ra_asn SET asn_access_type = 'CABLE' where asn = 3292;
  UPDATE ra_asn SET asn_access_type = 'CABLE' where asn = 20001;
  UPDATE ra_asn SET asn_access_type = 'CABLE' where asn = 42610;
  UPDATE ra_asn SET asn_access_type = 'CABLE' where asn = 20115;
  UPDATE ra_asn SET asn_access_type = 'CABLE' where asn = 2119;
  UPDATE ra_asn SET asn_access_type = 'CABLE' where asn = 29562;
  UPDATE ra_asn SET asn_access_type = 'CABLE' where asn = 12714;
  UPDATE ra_asn SET asn_access_type = 'CABLE' where asn = 16086;
  UPDATE ra_asn SET asn_access_type = 'CABLE' where asn = 6739;
  UPDATE ra_asn SET asn_access_type = 'CABLE' where asn = 6327;
  UPDATE ra_asn SET asn_access_type = 'CABLE' where asn = 22773;
  UPDATE ra_asn SET asn_access_type = 'CABLE' where asn = 10796;
  UPDATE ra_asn SET asn_access_type = 'CABLE' where asn = 20845;
  UPDATE ra_asn SET asn_access_type = 'CABLE' where asn = 25229;
  UPDATE ra_asn SET asn_access_type = 'CABLE' where asn = 11426;
  UPDATE ra_asn SET asn_access_type = 'CABLE' where asn = 11351;

  -- DSL
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 5607;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 12322;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 3320;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 3215;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 3265;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 2856;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 701;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 5432;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 20712;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 8402;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 35540;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 3209;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 3352;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 7018;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 3269;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 3303;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 6805;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 13184;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 6871;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 4739;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 12874;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 4788;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 13037;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 6799;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 15895;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 9031;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 3243;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 3741;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 5410;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 8737;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 8447;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 209;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 20676;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 3301;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 13030;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 8473;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 5610;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 35612;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 1267;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 12513;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 15557;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 4802;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 719;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 5617;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 16637;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 8422;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 13285;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 12576;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 9105;
  UPDATE ra_asn SET asn_access_type = 'DSL' where asn = 43234;

  UPDATE ra_asn SET asn_access_type = 'FIBRE' where asn = 29695;
  UPDATE ra_asn SET asn_access_type = 'FIBRE' where asn = 8767;
  UPDATE ra_asn SET asn_access_type = 'FIBRE' where asn = 15943;
  UPDATE ra_asn SET asn_access_type = 'FIBRE' where asn = 8708;
  UPDATE ra_asn SET asn_access_type = 'FIBRE' where asn = 44869;
  UPDATE ra_asn SET asn_access_type = 'FIBRE' where asn = 18106;

END TRANSACTION;
